# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd27c041313d3464e103e0a711ad8a3ac7f899307ce8a2e88d224e9a90b83308ddf2b3b3a00314d1942ec614465243ca2c8db7dc022cf24579e2c52e28855612

test:
  secret_key_base: ee5d574e44c01ef5c2f237704396c5e40cfdf513a523abe689363b24e22e8322282ae905284715f4bc7704cf42f6e985cf81fab84cb3516140eb0b0427a03250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
